# Generated by Django 5.1.1 on 2025-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=1000, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
