# Generated by Django 5.1.1 on 2025-08-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Coming Soon', 'Coming Soon')], max_length=20, null=True)),
            ],
        ),
    ]
