# Generated by Django 5.1.1 on 2025-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshopapp', '0003_product_quantity_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
